### PR TITLE
'emailhtml'

### PR DESCRIPTION
**Pull request by syedsimanta03**
Please check

### CODE REVIEW

**Comment by dmitrizagidulin** [comment]
Implements issue https://github.com/xrchat/xrchat-server/issues/175

**Comment by dmitrizagidulin** [comment]
@syedsimanta03 When testing, I get the following error:

Screen Shot 2020-05-27 at 6 18 45 PM

It looks like the email template has not been converted from `.html` to `.pug`. Please convert (or otherwise fix).

**Comment by syedsimanta03** [comment]
> @syedsimanta03 When testing, I get the following error:
> 
> Screen Shot 2020-05-27 at 6 18 45 PM
> 
> It looks like the email template has not been converted from `.html` to `.pug`. Please convert (or otherwise fix).

I was advised to push HTML, Please check PUG https://github.com/xrchat/xrchat-server/pull/192

**Comment by dmitrizagidulin** [comment]
Superceded by PR #192. Closing.

**Pull request closed without merging**
